image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY: registry.gitlab.com
  DOCKER_USER: $CI_REGISTRY_USER
  DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u "$DOCKER_USER" --password-stdin
    - docker build -t vidya-microservice .
    - docker tag vidya-microservice $DOCKER_REGISTRY/projects-guilherme/vidya-machine-learning-developer-practical-test:latest
    - docker push $DOCKER_REGISTRY/projects-guilherme/vidya-machine-learning-developer-practical-test:latest
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker pull $DOCKER_REGISTRY/projects-guilherme/vidya-machine-learning-developer-practical-test:latest
    - docker run -d --name vidya-microservice -p 5000:5000 $DOCKER_REGISTRY/projects-guilherme/vidya-machine-learning-developer-practical-test:latest
  only:
    - main